---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-accelerated-bridge-cni-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: accelerated-bridge
spec:
  template:
    metadata:
      labels:
        tier: node
        app: accelerated-bridge
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-accelerated-bridge-cni
        image: ghcr.io/k8snetworkplumbingwg/accelerated-bridge-cni:0.3.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
